In [233]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [234]:
import numpy as np

In [235]:

lst=list(range(1,25))
arr=np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [236]:
#arrange() - used to create the array
import numpy as np     #1D - array

In [237]:
arr= np.arange(1,25)  #arrange():used to create the array
arr  #single dimension array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [238]:
#creating numpy array

arr=np.array([1,2,3,4])

lst=list(range(1,20))
print(lst)
print(arr)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[1 2 3 4]


In [239]:
#creating numpy array

arr=np.array([1,2,3,4])

lst=list(range(5))
print(lst)
print(arr)  # isme array print nahi hai {array([1, 2, 3, 4])}

[0, 1, 2, 3, 4]
[1 2 3 4]


In [240]:
#creating numpy array

arr=np.array([1,2,3,4])

lst=list(range(5))
print(lst)
print(arr)
arr   # array print kar raha hai {array([1, 2, 3, 4])}

[0, 1, 2, 3, 4]
[1 2 3 4]


array([1, 2, 3, 4])

In [241]:
#2d array
import numpy as np
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [242]:
#2d array

arr=np.array([[1,2,3],[4,5,6],[5,6,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 8]])

In [243]:
#2d array
arr=np.array([[1,2,3],[4,5,6]]), ([[12,4,5],[2,34,4]])
arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 [[12, 4, 5], [2, 34, 4]])

In [244]:
#2d array
arr=np.array(([1,2,3],[4,5,6])), (([12,4,5],[2,34,4]))
print(arr)

(array([[1, 2, 3],
       [4, 5, 6]]), ([12, 4, 5], [2, 34, 4]))


In [245]:
#2d array
arr=np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
#creating a 3d array (2 blocks), 3 rows, 4 columns )
arr= np.array([[(1,2,3,4),(5,6,7,8),(9,10,11,12)],[(13,14,15,16),(17,18,19,20),(21,22,23,24)]])
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [247]:
#creating a 3d array (2 blocks), 3 rows, 4 columns )
arr= np.array(([(1,2,3,4),(5,6,7,8),(9,10,11,12)]))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [248]:
#create ones

arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [249]:
arr= np.linspace(1,10,5)

In [250]:
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [251]:
arr= np.linspace(3,545,6)  #linspace for the 6 values between 3 and 545
arr

array([  3. , 111.4, 219.8, 328.2, 436.6, 545. ])

In [252]:
#linspace() used to create array in the equal intervals
arr= np.linspace(1,10,5).reshape(5,1)   
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

# range fn , arrange fn, zeros fn, linspace, reshape

In [253]:
arr = np.arange(0,30).reshape(3,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [254]:
arr.reshape(3,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [255]:
arr=np.random.random((10))  #genrate 10 random values
arr

array([0.0323948 , 0.56473313, 0.28227846, 0.59297782, 0.76563558,
       0.70870589, 0.42620161, 0.55097166, 0.26349134, 0.30224258])

In [256]:
arr=np.random.random((5,2))
arr

array([[0.0348381 , 0.64821867],
       [0.3942526 , 0.22580206],
       [0.84347353, 0.09501837],
       [0.18463525, 0.07577011],
       [0.88164909, 0.92694352]])

In [257]:
# Create a 2D array
arr = np.arange(15).reshape(3, 5)  # Shape (3,5)

# Convert 2D to 3D
arr_3d = arr.reshape(3, 5, 1)  # Adding a new dimension

print("Original 2D Array:")
print(arr)
print("\nConverted 3D Array:")
print(arr_3d)

Original 2D Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Converted 3D Array:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]


In [258]:
#reshape initialization
arr=np.random.randint(1,5,9)
arr

array([2, 4, 2, 2, 3, 4, 2, 2, 3])

In [259]:
arr.dtype  #check data type

dtype('int32')

In [260]:
arr=np.random.randint(1,5,(3,3))
arr

array([[3, 1, 2],
       [3, 1, 3],
       [3, 1, 2]])

In [261]:
arr=np.random.randint(1,5,(3,4,4))
arr

array([[[1, 1, 3, 4],
        [2, 4, 4, 1],
        [2, 3, 4, 1],
        [1, 1, 2, 3]],

       [[2, 3, 3, 1],
        [3, 1, 4, 4],
        [1, 4, 4, 3],
        [2, 4, 1, 3]],

       [[2, 1, 2, 2],
        [1, 3, 2, 2],
        [4, 3, 2, 2],
        [1, 3, 2, 3]]])

In [262]:
arr= np.random.random(10)  
arr

array([0.31797201, 0.55083961, 0.02220501, 0.80640174, 0.81632882,
       0.85336348, 0.45531727, 0.84414624, 0.77009378, 0.75691084])

In [263]:
arr= np.random.randint(10)
arr

6

In [264]:
arr= np.random.random((5,2))  #define only 10 element
arr

array([[0.80393338, 0.22389957],
       [0.10877802, 0.86185902],
       [0.81874148, 0.4140982 ],
       [0.01027653, 0.57521635],
       [0.22975733, 0.71177825]])

In [265]:
arr=np.arange(60).reshape(10,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [266]:
arr=np.arange(60).reshape(10,6)
arr
arr.dtype

dtype('int32')

In [267]:
arr=np.arange(60).reshape(10,6)
print(arr)
arr.dtype

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [268]:
arr=np.arange(60).reshape(10,6)
arr
arr.dtype
arr.ndim
arr.size
arr.shape

(10, 6)

In [269]:
arr=np.arange(60).reshape(10,6)    #niche sabhi m print lagane se baki sabhi ke output aa gaye
print(arr)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(arr.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
int32
2
60
(10, 6)


In [270]:
#convert 2d or 3d in 1d
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [271]:
arr.ravel()  #convert in linear form in 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [272]:
lst=list(range(1,8))
arr=np.array(list)
arr

array(<class 'list'>, dtype=object)

In [273]:
lst=([1,2,3],[4,5,6])
arr=np.array(lst)
arr.shape           # shape

(2, 3)

In [274]:
lst=([1,2,3],[4,5,6])
arr=np.array(lst)
arr                     # isme shape nahi likha hai

array([[1, 2, 3],
       [4, 5, 6]])

In [275]:
arr.T.shape  #t=transpose shape

(3, 2)

In [276]:
arr.T  # generate transpose array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [277]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [278]:
arr.ndim  #dimension

2

In [279]:
lst=[1,2,3,4,5,1]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 1])

In [280]:
type(lst)

list

In [281]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 1])

In [282]:
type(arr)

numpy.ndarray

In [283]:
arr=np.array((1,2,3))
arr

array([1, 2, 3])

In [284]:
lst=list(range(0,20))    #to create list using array function
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [285]:
arr

array([1, 2, 3])

In [286]:
np.zeros((2,3)) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [287]:
arr=np.zeros((2,3)) 
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [288]:
#slicing and indexing
#index(0) and indexing (1)

arr=np.ones((10))
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [289]:
arr=np.ones((4,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [290]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [291]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [292]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [293]:
arr=np.random.randint(1,5,9)     # 1d array
arr

array([2, 4, 1, 2, 1, 4, 1, 3, 2])

In [294]:
arr=np.random.random((3,3))
arr

array([[0.05528812, 0.68200472, 0.56134127],
       [0.91669456, 0.17758061, 0.60172265],
       [0.36405619, 0.86884349, 0.93871076]])

In [295]:
arr.shape

(3, 3)

In [296]:
arr.dtype

dtype('float64')

In [297]:
arr.size

9

In [298]:
arr.ndim  # ndim= number of direction

2

In [299]:
arr.flatten()

array([0.05528812, 0.68200472, 0.56134127, 0.91669456, 0.17758061,
       0.60172265, 0.36405619, 0.86884349, 0.93871076])

In [300]:
arr.ravel()

array([0.05528812, 0.68200472, 0.56134127, 0.91669456, 0.17758061,
       0.60172265, 0.36405619, 0.86884349, 0.93871076])

In [301]:
list_2d=[[1,2,3],[3,4,5]]
list_2d

[[1, 2, 3], [3, 4, 5]]

In [302]:
list_2d=[[1,2,3],[3,4,5]]
list_2d
arr=np.array(list_2d)
print(arr)

[[1 2 3]
 [3 4 5]]


In [303]:
arr.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [304]:
arr.shape

(2, 3)

In [305]:
arr=np.random.random(10)
arr

array([0.89342243, 0.69245707, 0.47402547, 0.80371012, 0.1354073 ,
       0.61783836, 0.22752895, 0.75215451, 0.52265318, 0.65656126])

In [306]:
arr[1]  #indexing

0.6924570664202622

In [307]:
arr[2:9]  #slicing start from 2 and ends at 8

array([0.47402547, 0.80371012, 0.1354073 , 0.61783836, 0.22752895,
       0.75215451, 0.52265318])

In [308]:
arr=np.arange(60)   #indexing zero se start hoti hai or position one se start hogi
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [309]:
arr[3:10]

array([3, 4, 5, 6, 7, 8, 9])

In [310]:
arr[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [311]:
arr=arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [312]:
arr[1]

array([5, 6, 7, 8, 9])

In [313]:
arr[1,1]

6

In [314]:
arr[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [315]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [316]:
arr[0:5,1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [317]:
arr[0:,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21],
       [26],
       [31],
       [36],
       [41],
       [46],
       [51],
       [56]])

In [318]:
arr[11,4]  #last element access

59

In [319]:
arr[11][-1]

59

In [320]:
arr[-1][-1]

59

In [321]:
arr[2,2]

12

In [322]:
arr[:4][1]

array([5, 6, 7, 8, 9])

In [323]:
arr[4,2]=100  #replace the 4th row 3rd element by 100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [324]:
arr=np.arange(225)
arr=arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [325]:
arr.shape

(5, 15, 3)

In [326]:
arr[0][2:7][0]

array([6, 7, 8])

In [327]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [328]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [329]:
arr +2

array([[[  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [ 20,  21,  22],
        [ 23,  24,  25],
        [ 26,  27,  28],
        [ 29,  30,  31],
        [ 32,  33,  34],
        [ 35,  36,  37],
        [ 38,  39,  40],
        [ 41,  42,  43],
        [ 44,  45,  46]],

       [[ 47,  48,  49],
        [ 50,  51,  52],
        [ 53,  54,  55],
        [ 56,  57,  58],
        [ 59,  60,  61],
        [ 62,  63,  64],
        [ 65,  66,  67],
        [ 68,  69,  70],
        [ 71,  72,  73],
        [ 74,  75,  76],
        [ 77,  78,  79],
        [ 80,  81,  82],
        [ 83,  84,  85],
        [ 86,  87,  88],
        [ 89,  90,  91]],

       [[ 92,  93,  94],
        [ 95,  96,  97],
        [ 98,  99, 100],
        [101, 102, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 118],
        [119, 120, 12

In [330]:
arr *2

array([[[  0,   2,   4],
        [  6,   8,  10],
        [ 12,  14,  16],
        [ 18,  20,  22],
        [ 24,  26,  28],
        [ 30,  32,  34],
        [ 36,  38,  40],
        [ 42,  44,  46],
        [ 48,  50,  52],
        [ 54,  56,  58],
        [ 60,  62,  64],
        [ 66,  68,  70],
        [ 72,  74,  76],
        [ 78,  80,  82],
        [ 84,  86,  88]],

       [[ 90,  92,  94],
        [ 96,  98, 100],
        [102, 104, 106],
        [108, 110, 112],
        [114, 116, 118],
        [120, 122, 124],
        [126, 128, 130],
        [132, 134, 136],
        [138, 140, 142],
        [144, 146, 148],
        [150, 152, 154],
        [156, 158, 160],
        [162, 164, 166],
        [168, 170, 172],
        [174, 176, 178]],

       [[180, 182, 184],
        [186, 188, 190],
        [192, 194, 196],
        [198, 200, 202],
        [204, 206, 208],
        [210, 212, 214],
        [216, 218, 220],
        [222, 224, 226],
        [228, 230, 232],
        [234, 236, 23

In [331]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [332]:
arr=np.arange(60)

In [333]:
arr=arr.reshape(12,5)

In [334]:
arr[2,2]

12

In [335]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [336]:
arr[2,3]

13

In [337]:
arr=arr.reshape(12,5)

In [338]:
arr1=np.arange(60)

In [339]:
arr1=arr1.reshape(12,5)

In [340]:
arr+arr1

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [347]:
listx=[1,2,3,4]
listy=[5,6,7,8]
listx+listy

[1, 2, 3, 4, 5, 6, 7, 8]

In [348]:
arr1=np.array(listx)
arr2=np.array(listy)
arr=arr1+arr2
arr

array([ 6,  8, 10, 12])

In [349]:
arr=arr1*arr2
arr

array([ 5, 12, 21, 32])